import { ROUTES as BASE } from "@/constants/routes";

/**
 * Institution platform routes.
 */
export const INSTITUTION_ROUTES = {
  root: "/institution",
  dashboard: "/institution/dashboard",
  admissions: "/institution/admissions",
  admissionsAnalytics: "/institution/admissions/analytics",
  admissionsReports: "/institution/admissions/reports",
  students: "/institution/students",
  studentAnalytics: "/institution/students/analytics",
  studentReports: "/institution/students/reports",
  studentTalent: "/institution/students/talent",
  studentDetail: (id: string) => `/institution/students/${id}`,
  faculty: "/institution/faculty",
  facultyAnalytics: "/institution/faculty/analytics",
  facultyReports: "/institution/faculty/reports",
  departments: "/institution/departments",
  courses: "/institution/courses",
  academics: "/institution/academics",
  academicsAnalytics: "/institution/academics/analytics",
  academicsReports: "/institution/academics/reports",
  placements: "/institution/placements",
  placementsAnalytics: "/institution/placements/analytics",
  placementsReports: "/institution/placements/reports",
  research: "/institution/research",
  researchAnalytics: "/institution/research/analytics",
  researchReports: "/institution/research/reports",
  incubation: "/institution/incubation",
  alumni: "/institution/alumni",
  alumniAnalytics: "/institution/alumni/analytics",
  alumniReports: "/institution/alumni/reports",
  industryNetwork: "/institution/industry-network",
  partnershipDetail: (id: string) => `/institution/partnerships/${id}`,
  events: "/institution/events",
  gallery: "/institution/gallery",
  announcements: "/institution/announcements",
  campus: "/institution/campus",
  campusAnalytics: "/institution/campus/analytics",
  campusReports: "/institution/campus/reports",
  analytics: "/institution/analytics",
  commandCenter: "/institution/command-center",
  commandCenterReports: "/institution/command-center/reports",
  reports: "/institution/reports",
  settings: "/institution/settings",
  help: "/institution/help",
  notifications: "/institution/notifications",
  profile: "/institution/profile",
  college: "/institution/college",
  school: "/institution/school",
  branches: "/institution/branches",
  subjects: "/institution/subjects",
  teachers: "/institution/teachers",
  classes: "/institution/classes",
  members: "/institution/members",
} as const;

export type InstitutionRoute =
  (typeof INSTITUTION_ROUTES)[keyof typeof INSTITUTION_ROUTES];

export const INSTITUTION_NAV = [
  { label: "Dashboard", href: INSTITUTION_ROUTES.dashboard, primary: true },
  { label: "Admissions", href: INSTITUTION_ROUTES.admissions },
  { label: "Students", href: INSTITUTION_ROUTES.students },
  { label: "Faculty", href: INSTITUTION_ROUTES.faculty },
  { label: "Departments", href: INSTITUTION_ROUTES.departments },
  { label: "Courses", href: INSTITUTION_ROUTES.courses },
  { label: "Placements", href: INSTITUTION_ROUTES.placements },
  { label: "Research", href: INSTITUTION_ROUTES.research },
  { label: "Incubation", href: INSTITUTION_ROUTES.incubation },
  { label: "Alumni", href: INSTITUTION_ROUTES.alumni },
  { label: "Industry Network", href: INSTITUTION_ROUTES.industryNetwork },
  { label: "Events", href: INSTITUTION_ROUTES.events },
  { label: "Gallery", href: INSTITUTION_ROUTES.gallery },
  { label: "Announcements", href: INSTITUTION_ROUTES.announcements },
  { label: "Analytics", href: INSTITUTION_ROUTES.commandCenter },
  { label: "Reports", href: INSTITUTION_ROUTES.reports },
  { label: "Settings", href: INSTITUTION_ROUTES.settings },
  { label: "Help", href: INSTITUTION_ROUTES.help },
] as const;

export const INSTITUTION_ACCOUNT_ROUTE = BASE.settings;
