const mongoose = require('mongoose');

const institutionSchema = new mongoose.Schema({
  ownerId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  slug: { type: String, unique: true, sparse: true, trim: true },
  name: { type: String, required: true, trim: true },
  status: { type: String, enum: ['pending', 'approved', 'suspended'], default: 'approved', index: true },
  institutionType: {
    type: String,
    enum: ['university', 'engineering', 'medical', 'college', 'school', 'training', 'bootcamp', 'other'],
    default: 'college',
    index: true,
  },
  establishedYear: { type: Number, default: null },
  ranking: { type: Number, default: null, index: true },
  verified: { type: Boolean, default: true },
  logo: { type: String, default: '' },
  banner: { type: String, default: '' },
  about: { type: String, default: '' },
  mission: { type: String, default: '' },
  vision: { type: String, default: '' },
  history: { type: String, default: '' },
  leadership: {
    chairmanMessage: { type: String, default: '' },
    principalMessage: { type: String, default: '' },
    directorMessage: { type: String, default: '' },
  },
  campus: {
    laboratories: { type: String, default: '' },
    library: { type: String, default: '' },
    hostels: { type: String, default: '' },
    sports: { type: String, default: '' },
    transportation: { type: String, default: '' },
    cafeteria: { type: String, default: '' },
    medical: { type: String, default: '' },
    hostelAvailable: { type: Boolean, default: false },
  },
  academicCalendar: { type: String, default: '' },
  placementTimeline: { type: String, default: '' },
  internshipsInfo: { type: String, default: '' },
  contact: {
    email: String,
    phone: String,
    website: String,
    address: String,
    city: String,
    state: String,
    country: String,
    pincode: String,
  },
  social: {
    linkedin: String,
    twitter: String,
    facebook: String,
    instagram: String,
    youtube: String,
  },
  location: { lat: Number, lng: Number },
  admissionInfo: { type: String, default: '' },
  scholarships: { type: String, default: '' },
  brochureUrl: { type: String, default: '' },
  facilities: [{ type: String }],
  achievements: [{ title: String, year: String, description: String }],
  research: [{ title: String, summary: String, url: String }],
  recruiters: [{ name: String, logo: String, package: String }],
  aiInsights: {
    bestCourses: [{ type: String }],
    trendingPrograms: [{ type: String }],
    industryDemand: { type: String, default: '' },
    placementForecast: { type: String, default: '' },
    salaryOutlook: { type: String, default: '' },
    futureSkills: [{ type: String }],
    admissionCompetition: { type: String, default: '' },
    careerOpportunities: [{ type: String }],
    summary: { type: String, default: '' },
    generatedAt: { type: Date },
  },
  stats: {
    studentCount: { type: Number, default: 0 },
    facultyCount: { type: Number, default: 0 },
    placementRate: { type: Number, default: 0 },
    highestPackage: { type: Number, default: 0 },
    averagePackage: { type: Number, default: 0 },
    visitors: { type: Number, default: 0 },
    followers: { type: Number, default: 0 },
    aiRating: { type: Number, default: 0 },
    applications: { type: Number, default: 0 },
    courseViews: { type: Number, default: 0 },
    galleryViews: { type: Number, default: 0 },
    placementViews: { type: Number, default: 0 },
    studentInterest: { type: Number, default: 0 },
  },
  isPublic: { type: Boolean, default: true },
}, { timestamps: true });

institutionSchema.index({ name: 'text', about: 'text', mission: 'text' });
institutionSchema.index({ 'contact.state': 1, 'contact.city': 1 });
institutionSchema.index({ 'stats.aiRating': -1 });
institutionSchema.index({ 'stats.placementRate': -1 });

module.exports = mongoose.model('Institution', institutionSchema);
